# Generated by Django 5.0.7 on 2024-07-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucional',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucional',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucional',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucional',
            name='logo_one',
            field=models.ImageField(blank=True, null=True, upload_to='institucional/'),
        ),
        migrations.AddField(
            model_name='institucional',
            name='logo_three',
            field=models.ImageField(blank=True, null=True, upload_to='institucional/'),
        ),
        migrations.AddField(
            model_name='institucional',
            name='logo_two',
            field=models.ImageField(blank=True, null=True, upload_to='institucional/'),
        ),
        migrations.AddField(
            model_name='institucional',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucional',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
