# Generated by Django 5.0.7 on 2024-07-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_institucional_address_institucional_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucional',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
